### ISSUE TITLE
Cannot access protected property

### ISSUE THREAD

**Issue by brescianicri** [749/modx_facebook_feed#1]
I recive this error:
PHP Fatal error:  Cannot access protected property Facebook\\Exceptions\\FacebookResponseException::$message in /var/www/www.xxx.com/core/components/facebook_feed/model/fb_feed/feed.class.php on line 212

**Comment by 749** [comment]
Which version of php and modx are you using?

**Comment by brescianicri** [comment]
MODX Revolution 2.5.1-pl
PHP Version 5.4.16

**Comment by 749** [comment]
I see the problem, will fix as soon as possible, however it seems you are getting a graph error. Did you set up the authentication token by opening the custom manager page, after you setup the correct application id and secret?

**Comment by 749** [comment]
The fixed version should be available on modx extras within the next few days, it's being looked over by moderators.
