### ISSUE TITLE
Graph Error: Invalid OAuth access token signature

### ISSUE THREAD

**Issue by lottaar** [749/modx_facebook_feed#10]
I've followed the instructions and tried making several different Facebook Apps but keep getting this error in the log and nothing is displayed on the page with [[!FB_Feed? &page=`<myPageID>`]]. The Access Token gets updated successfully.

(ERROR @ /Users/xx/Projekt/mamp_dev/core/components/facebook_feed/model/fb_feed/feed.class.php : 222) Graph Error: Invalid OAuth access token signature.

Using MODX 2.5.6 on localhost.

**Comment by 749** [comment]
Thank you for reporting this bug. I will need some additional information:

1. Which version of the plugin are you using?
2. Has the access_token been inserted into the settings?  
   Goto the System Settings > Change core to facebook_feed and check if the setting facebook_feed.access_token is not empty  
also it should look like this <numbers>|<numbers, letters and underscore>  
There should not be any "access_token=" infront of the string

**Comment by lottaar** [comment]
Sure :)

1. It's Facebook Feed 0.2.3-beta
2. It looks like this (I've replaced the numbers and letters in the token): {"access_token":"000000000000000|xxxxxxxxxxxxxxxxxxxx","token_type":"bearer"}

I manually removed everything apart from the actual token in facebook_feed.access_token and now the feed displays fine :)

**Comment by 749** [comment]
This is very troubling, facebook might have changed their API I'll have to have a look at it using the API explorer. For now if you want to get it to work just replace the current value with the numbers and letters in the format i posted earlier. the snippet should then work.

**Comment by 749** [comment]
I have updated the plugin, the newest version should now work correctly
