### ISSUE TITLE
Feature Request : Event Feed

### ISSUE THREAD

**Issue by neoneddy** [749/modx_facebook_feed#12]
Would be sweet to pull in Events

**Comment by 749** [comment]
I think events are separate from the feed, I would probably make a different snippet for it, as the call to the current snippet would get to messy otherwise. please let me know if that would be acceptable.

**Comment by neoneddy** [comment]
Sure, if you're offering.

**Comment by 749** [comment]
I will likely need a couple of days though, I'll see what I can get done this weekend

**Comment by neoneddy** [comment]
Thanks, I'll give this a try.
