### ISSUE TITLE
Feed stoped working

### ISSUE THREAD

**Issue by sillymonkeydesigns** [749/modx_facebook_feed#14]
I installed plugin yesterday and it was working just fine. Showing the 4 posts with images ect. Then i installed JSONdurolo for the twitter feed and after that the facebook feed stopped working. I checked all keys and tokens etc but cannot find the issue

**Comment by sillymonkeydesigns** [comment]
Manged to fix issue by using different access token. I used user token witch expired so changed it to app token.

**Comment by 749** [comment]
Does the issue persist? or can i close the ticket?
