### ISSUE TITLE
Target "posts" instead of "feed"

### ISSUE THREAD

**Issue by matdave** [749/modx_facebook_feed#16]
Nice start to this app.  I just took a look through the code and noticed it's targeting _feed_ instead of _posts_.  You might want to set an option for that, because _feed_ can get really "loud".

**Comment by 749** [comment]
Thanks for reviewing the code, the original client that i wrote this plugin for wanted to have the entire feed minus a couple of posts, so I actually added some filters which remove the unwanted posts.
I could add an option to the snippet to select the posts instead of feed if you need that
