### ISSUE TITLE
How to make this work after Sept 4th 2019

### ISSUE THREAD

**Issue by lottaar** [749/modx_facebook_feed#19]
Since Facebook changing its policies the feed can no longer be displayed. Missing "Page Public Content Access" apparently. Is there any way to make it work?

**Comment by jenswittmann** [comment]
I think you need to verify your Facebook APP: <https://developers.facebook.com/apps>
If i get it done, i'll give you an update!

**Comment by 749** [comment]
Unfortunately the only way to get past this restriction is to verify your application, it is only possible with a business account on facebook.
I am currently in the process of doing this for a client. Will update the readme afterwards.

**Comment by lottaar** [comment]
Did anyone have any luck with verifying their Facebook application? It was a very long winded procedure I think and I had to give up in the end :(
