### ISSUE TITLE
Visitor posts also showing

### ISSUE THREAD

**Issue by mdehaan** [749/modx_facebook_feed#2]
<img width="684" alt="visitor-posts" src="https://cloud.githubusercontent.com/assets/581336/22969262/2324dc50-f36e-11e6-9de3-2a28bc033276.png">

It also shows visitor postst.
This is not wanted in my case.
Maybe it should be controllable with a property &showVisitorPosts=`0`.

**Comment by 749** [comment]
I'll have to look into the facebook api to see whether they can be filtered out, maybe I could detect it by author and add an &author='<your_facebook_name>'

**Comment by 749** [comment]
I have found a way to select posts by author, however it will need to be the Id of the authors. Will add this feature soon, as I may have this issue in the future as well

**Comment by 749** [comment]
I have tested the authors attribute locally with your site, i believe the correct code will be

``[[!FB_Feed? &page=`olympiaradionl` &authors=`1393384134219928`]]``.

I will update the plugin in the modx database as soon as possible, however it will take up to a week until ModX moderators have allowed the changes

**Comment by 749** [comment]
The new version is available on modx extras
