### ISSUE TITLE
Feature request: offset property

### ISSUE THREAD

**Issue by mdehaan** [749/modx_facebook_feed#3]
It would be nice to have an offset property.

**Comment by 749** [comment]
I am unsure as to the functionality of such an offset property, could you explain in a little more detail what you need?

**Comment by mdehaan** [comment]
For example I would like the most recent 3 items bigger and the following smaller.
Offeset would allow me to exclude/skip the first 3 items on the second snippet call.
```
[[!FB_Feed? &page=`olympiaradionl` &limit=`3` &tpl=`facebook-feed-tiles-item-big`]]
[[!FB_Feed? &page=`olympiaradionl` &offset=`3` &limit=`20` &tpl=`facebook-feed-tiles-item-small`]]
```

**Comment by 749** [comment]
you can solve this using css, however i will add the support as soon as possible
